apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default .Release.Name }}
spec:
  ports:
  - port: 80
    name: nginx
  - port: 3001  
    name: go
  selector:
    app: {{ .Values.name | default .Release.Name }}
